### ISSUE TITLE
Python script's name was changed

### ISSUE THREAD

**Issue by LenaicTerrier** [dpelle/vim-Grammalecte#13]
Greetings,

**Grammalecte**'s commit [099f103bb1f75b48](http://code.grammalecte.net:8080/ci/099f103bb1f75b48) has moved `cli.py` to `grammalecte-cli.py`. This change should be acknowledge in **vim-Grammalecte**'s `README.md`.

From
```
let g:grammalecte_cli_py='~/Downloads/Grammalecte-fr-v0.5.14/pythonpath/cli.py'
```
to
```
let g:grammalecte_cli_py='~/Downloads/Grammalecte-fr-v0.6.1/pythonpath/grammalecte-cli.py'
```
as version `0.6.1` is the first version with this change.

If necessary, I'm willing to setup a pull request to close this issue.

Lénaïc

**Comment by tarikgraba** [comment]
I think the whole section **"Installing Grammalecte"** should be revised as the download link should be:
https://grammalecte.net/#download
And the cli & server version (zip) should be used instead of the LibreOffice/OpenOffice version (oxt) of the plugin.

**Comment by dpelle** [comment]
The file `doc/Grammalecte.txt` was updated recently.
It fixes the renaming of file cli.py -> grammalecte-cli.py among other things.
Closing.
