### ISSUE TITLE
Does not work with grammalecte 1.12.0

### ISSUE THREAD

**Issue by misaflo** [dpelle/vim-Grammalecte#22]
Hello,

I have this error on GrammalecteCheck with grammalecte 1.12.0 (no problem with 1.11.0):

    Erreur détectée en traitant function <SNR>40_GrammalecteCheck :
    ligne   43 :
    Error while decoding json output of Grammalecte. Try running Grammalecte in command line to diagnose.

I use neovim 0.4.4.

When using grammalecte in cli (`python3 ./grammalecte-cli.py`), it works.

**Comment by ArchangeGabriel** [comment]
I think it has been fixed in grammalecte 1.12.1 or 2, can you confirm?

**Comment by misaflo** [comment]
Yes ! It works with 1.12.2.
I hadn't seen that the latest version was 1.12.2.
