### ISSUE TITLE
Changement de nom de domaine.

### ISSUE THREAD

**Issue by Naheulf** [dpelle/vim-Grammalecte#24]
Bonjour,

Les deux sites http://dicollecte.org (le dictionnaire) et https://grammalecte.net ont été regroupés sur ce second nom de domaine. Serait-il possible de mettre à jour les différentes URLs présentes dans le code du plugin avec des liens qui ne passent pas par une redirection ?

**Comment by dpelle** [comment]
@Naheulf wrote :

> Serait-il possible de mettre à jour les différentes URLs

Done in f761883adcd4db756af096fccef714ceceaba73f
