### ISSUE TITLE
Mise à jour de la doc

### ISSUE THREAD

**Issue by Naheulf** [dpelle/vim-Grammalecte#25]
Dans les derniers changements, une partie du fichier  /plugin/Grammalecte.vim à été externalisé dans le fichier /autoload/grammalecte.vim. Serait-il possible de mettre à jour la doc pour correspondre à ces derniers changements ?

(Notons au passage la différence de casse dans le nom de ce dernier fichier)

**Comment by dpelle** [comment]
@Naheulf : 

> Serait-il possible de mettre à jour la doc pour correspondre à ces derniers changements ?

Done in 73e872b9257856ab097fa85e7c4653a298450a18

Thanks for reporting it.
