### ISSUE TITLE
json_decode missing

### ISSUE THREAD

**Issue by Elm7** [dpelle/vim-Grammalecte#5]
Hi and thank you for the plugin.
I do not get over the "json_decode" availability test although my gvim and qvim version are 7.4.56
How do I get that "json_decode" on Debian jessie latest to be found by the plugin ? thx

**Comment by dpelle** [comment]
Vim-7.4.56 is too old for vim-Grammalecte.  It requires json functions.
vim-7.4.056 is from Nov 2013, so it's quite old.
You're missing a lot of bug fixes and new features.

My advice is the checkout the latest source code of Vim (8.0.587)
and build it. It's quite easy on Debian or Ubuntu:

```
$ sudo apt-get install git
$ sudo apt-get build-dep vim-gnome
$ git clone https://github.com/vim/vim.git
$ cd vim
$ ./configure --with-features=huge --enable-gui=gtk2 --enable-python3interp=yes
$ make -j8
$ make test
$ sudo make install
```

**Comment by Elm7** [comment]
Hello, thanks for the advice. My old version is the version of debian stable (jessie), that should update in a few weeks (debian stretch) so I'll try then. Have nice days.

**Comment by dpelle** [comment]
> My old version is the version of debian stable (jessie), that should update
> in a few weeks (debian stretch) so I'll try then. Have nice days.

Yes, I see that Debian stretch uses vim-8.0.0197, so it should work fine.
